// src/CommandPalette.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { fuzzyScore } from './fuzzy';

export interface Command {
  id: string;
  title: string;
  hint?: string;
  current?: boolean;
  keywords?: string;
  run: () => void;
}

interface CommandPaletteProps {
  commands: Command[];
  onClose: () => void;
}

export default function CommandPalette({
  commands,
  onClose,
}: CommandPaletteProps) {
  const [query, setQuery] = useState('');
  const [index, setIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const listRef = useRef<HTMLUListElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);

  const matches = useMemo(() => {
    const scored: { c: Command; s: number }[] = [];
    for (const c of commands) {
      const s = fuzzyScore(query, `${c.title} ${c.keywords ?? ''}`);
      if (s != null) scored.push({ c, s });
    }
    scored.sort((a, b) => b.s - a.s);
    return scored;
  }, [commands, query]);

  const sel = Math.min(index, matches.length - 1);

  useEffect(() => {
    // Defer focus past first paint: focusing the input blurs the math-field,
    // and MathLive's blur work plus the native focus() layout would otherwise
    // run before the palette's first paint and delay it.
    const t0 = setTimeout(() => inputRef.current?.focus(), 0);
    // The deferred MathLive refocus lands up to ~60ms after the field was
    // focused; re-assert input focus just past that window in case a steal
    // slipped past the focusout trap below.
    const t1 = setTimeout(() => inputRef.current?.focus(), 70);
    return () => {
      clearTimeout(t0);
      clearTimeout(t1);
    };
  }, []);

  // Escape must close even if focus has drifted out of the input.
  useEffect(() => {
    const onKeydown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onClose();
        return;
      }
      const input = inputRef.current;
      if (input && document.activeElement !== input) {
        // Focus hasn't landed yet (it's deferred past first paint); a key
        // arriving now would otherwise be typed into the still-focused
        // math-field. Take focus and swallow the event — replaying the key
        // into the query if it was a printable character.
        input.focus();
        e.preventDefault();
        e.stopPropagation();
        if (e.key.length === 1 && !e.ctrlKey && !e.metaKey && !e.altKey) {
          setQuery((q) => q + e.key);
          setIndex(0);
        }
      }
    };
    window.addEventListener('keydown', onKeydown, true);
    return () => window.removeEventListener('keydown', onKeydown, true);
  }, [onClose]);

  const didMount = useRef(false);
  useEffect(() => {
    // Skip the mount run — scrollIntoView forces a synchronous document
    // layout, which would sit before the palette's first paint.
    if (!didMount.current) {
      didMount.current = true;
      return;
    }
    listRef.current
      ?.querySelector('.cmd-item.selected')
      ?.scrollIntoView({ block: 'nearest' });
  }, [sel]);

  // MathLive re-asserts focus on a ~60ms timer after a field is focused,
  // which can steal focus from the palette when it was opened right after
  // editing a cell — so keep focus inside while the palette is open.
  const onFocusOut = (e: React.FocusEvent) => {
    const root = rootRef.current;
    if (root && !root.contains(e.relatedTarget as Node))
      setTimeout(() => inputRef.current?.focus(), 0);
  };

  const pick = (c: Command) => {
    c.run();
    onClose();
  };

  const onKeydown = (e: React.KeyboardEvent) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setIndex((i) => Math.min(i + 1, matches.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setIndex((i) => Math.max(i - 1, 0));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const m = matches[sel];
      if (m) pick(m.c);
    } else if (e.key === 'Escape') {
      e.preventDefault();
      onClose();
    }
  };

  return (
    <div className="palette-backdrop" onClick={onClose}>
      <div
        ref={rootRef}
        className="palette"
        role="dialog"
        aria-modal="true"
        aria-label="Command palette"
        onClick={(e) => e.stopPropagation()}
        onBlur={onFocusOut}
      >
        <input
          ref={inputRef}
          className="palette-input"
          placeholder="Type a command…"
          value={query}
          role="combobox"
          aria-expanded="true"
          aria-controls="palette-list"
          aria-activedescendant={sel >= 0 ? `palette-opt-${sel}` : undefined}
          onChange={(e) => {
            setQuery(e.target.value);
            setIndex(0);
          }}
          onKeyDown={onKeydown}
        />
        <ul className="palette-list" id="palette-list" role="listbox" ref={listRef}>
          {matches.map((m, i) => (
            <li
              key={m.c.id}
              id={`palette-opt-${i}`}
              role="option"
              aria-selected={i === sel}
              className={i === sel ? 'cmd-item selected' : 'cmd-item'}
              onMouseEnter={() => setIndex(i)}
              onClick={() => pick(m.c)}
            >
              <span className="cmd-title">{m.c.title}</span>
              {m.c.current && <span className="cmd-current">✓</span>}
              {m.c.hint && <kbd className="cmd-hint">{m.c.hint}</kbd>}
            </li>
          ))}
          {matches.length === 0 && (
            <li className="cmd-empty">No matching commands</li>
          )}
        </ul>
        <div className="palette-footer">
          ↑↓ navigate · Enter run · Esc close
        </div>
      </div>
    </div>
  );
}

// src/components/CommandPalette.tsx
import { createEffect, createMemo, createSignal, onCleanup, onMount, Index } from 'solid-js';
import { fuzzyScore } from '../fuzzy';
import type { Command } from '../commands';
import { appStore } from '../store';

// Permanently mounted: opening is a visibility flip + focus(), not a mount
// — cold-open cost is gone by design (challenges.md §8).
export default function CommandPalette(props: { commands: Command[] }) {
  const [query, setQuery] = createSignal('');
  const [index, setIndex] = createSignal(0);
  let inputRef!: HTMLInputElement;
  let listRef!: HTMLUListElement;
  let rootRef!: HTMLDivElement;

  const matches = createMemo(() => {
    const scored: { c: Command; s: number }[] = [];
    for (const c of props.commands) {
      const s = fuzzyScore(query(), `${c.title} ${c.keywords ?? ''}`);
      if (s != null) scored.push({ c, s });
    }
    scored.sort((a, b) => b.s - a.s);
    return scored;
  });

  const sel = () => Math.min(index(), matches().length - 1);
  const close = () => appStore.setPaletteOpen(false);

  // On open: reset state and focus the input. The field is already laid
  // out (always mounted), so focus() is cheap — but MathLive re-asserts
  // cell focus on a ~60ms timer after a field was focused, so re-assert
  // once just past that window.
  createEffect(() => {
    if (!appStore.paletteOpen()) return;
    setQuery('');
    setIndex(0);
    inputRef.focus();
    const t = setTimeout(() => {
      // The palette may have closed within the window — a stale refocus on
      // the still-mounted input would steal focus back from the cell.
      if (appStore.paletteOpen()) inputRef.focus();
    }, 70);
    onCleanup(() => clearTimeout(t));
  });

  // Escape must close even if focus has drifted out of the input.
  onMount(() => {
    const onKeydown = (e: KeyboardEvent) => {
      if (appStore.paletteOpen() && e.key === 'Escape') {
        e.preventDefault();
        close();
      }
    };
    window.addEventListener('keydown', onKeydown, true);
    onCleanup(() => window.removeEventListener('keydown', onKeydown, true));
  });

  createEffect(() => {
    const i = sel();
    if (!appStore.paletteOpen() || i < 0) return;
    listRef
      .querySelector('.cmd-item.selected')
      ?.scrollIntoView({ block: 'nearest' });
  });

  // Keep focus inside while the palette is open: MathLive's deferred
  // refocus can steal it when the palette opened right after editing.
  // Re-check openness inside the timeout — commands close the palette while
  // focus is already moving to a cell, and the mounted input must not take
  // it back.
  const onFocusOut = (e: FocusEvent) => {
    if (
      appStore.paletteOpen() &&
      rootRef &&
      !rootRef.contains(e.relatedTarget as Node)
    )
      setTimeout(() => {
        if (appStore.paletteOpen()) inputRef.focus();
      }, 0);
  };

  const pick = (c: Command) => {
    c.run();
    close();
  };

  const onKeydown = (e: KeyboardEvent) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setIndex((i) => Math.min(i + 1, matches().length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setIndex((i) => Math.max(i - 1, 0));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const m = matches()[sel()];
      if (m) pick(m.c);
    }
    // Escape is handled by the window capture listener.
  };

  return (
    <div
      class="palette-backdrop"
      classList={{ open: appStore.paletteOpen() }}
      onClick={close}
    >
      <div
        ref={(el) => (rootRef = el)}
        class="palette"
        role="dialog"
        aria-modal="true"
        aria-label="Command palette"
        onClick={(e) => e.stopPropagation()}
        onFocusOut={onFocusOut}
      >
        <input
          ref={(el) => (inputRef = el)}
          class="palette-input"
          placeholder="Type a command…"
          value={query()}
          role="combobox"
          aria-expanded="true"
          aria-controls="palette-list"
          aria-activedescendant={sel() >= 0 ? `palette-opt-${sel()}` : undefined}
          onInput={(e) => {
            setQuery(e.currentTarget.value);
            setIndex(0);
          }}
          onKeyDown={onKeydown}
        />
        <ul class="palette-list" id="palette-list" role="listbox" ref={(el) => (listRef = el)}>
          <Index each={matches()}>
            {(m, i) => (
              <li
                id={`palette-opt-${i}`}
                role="option"
                aria-selected={i === sel()}
                class={i === sel() ? 'cmd-item selected' : 'cmd-item'}
                onMouseEnter={() => setIndex(i)}
                onClick={() => pick(m().c)}
              >
                <span class="cmd-title">{m().c.title}</span>
                {m().c.current && <span class="cmd-current">✓</span>}
                {m().c.hint && <kbd class="cmd-hint">{m().c.hint}</kbd>}
              </li>
            )}
          </Index>
          {matches().length === 0 && (
            <li class="cmd-empty">No matching commands</li>
          )}
        </ul>
        <div class="palette-footer">↑↓ navigate · Enter run · Esc close</div>
      </div>
    </div>
  );
}
